build: externalize react/jsx-runtime
FarazzShaikh/THREE-CustomShaderMaterial pull request #69
Opened 2024-11-22 21:42 UTC by KlotzJesse

Optimizes bundeling sizes, because at the moment react/jsx-runtime is being bundled unnecessary leading to a overhead in production, by externalizing react/jsx-runtime and also for the future react-dom/client

Would be awesome for having a quick merge, because no breaking change, no problem, just removes overhead, reduce bundle size, and also provides a fix.

Also fixes #66

2024-11-22 21:47 UTC, FarazzShaikh commented
Thanks! Will review it tomorrow. Have you tested it as a fix for 66?

2024-11-22 21:48 UTC, FarazzShaikh requested changes

2024-11-22 21:48 UTC, FarazzShaikh commented on package/vite.config.ts
> +      xternal: ["react", "react/jsx-runtime", "react-dom", "react-dom/client", "three", "@react-three/fiber"],
Is this not a typo? Shouldn’t it be “external”

2024-11-22 21:52 UTC, KlotzJesse reviewed
yeah, great catch thanks

2024-11-22 21:54 UTC, KlotzJesse commented
> Thanks! Will review it tomorrow. Have you tested it as a fix for 66?

tbh no, had no time, but had this fixed for several other repos. you can verify the unecessary bundle here:
https://unpkg.com/three-custom-shader-material/three-custom-shader-material.es.js -> see react-jsx-runtime and search for ReactCurrentDispatch.

You will see, it bundles the use of __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner e.g. in the dist of the package in npm

The reason why it breaks is because __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED were changed in react 19, which leads to a problem and react version mismatch, because __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED is undefined, and nextjs15 is using react 19 rc

2024-11-22 21:56 UTC, FarazzShaikh commented
I see, thank you very much. I will do some additional verification before merging shortly.

2025-01-04 01:25 UTC, gdomaradzki commented
Any news on this?

2025-01-31 12:52 UTC, fully-john commented on package/vite.config.ts
> +      xternal: ["react", "react/jsx-runtime", "react-dom", "react-dom/client", "three", "@react-three/fiber"],
This was addressed in 12f4e5fcbd4fe359eef57cb23ff3377d5380b92e, no?
This could be marked as resolved. I'm currently on a React19 Next15 project and would love to get this into my project!

2025-01-31 13:17 UTC, fully-john commented
Both drei and fiber now has working versions on rc. Any possibility to merge this on a relese candidate version on npm as well? Once fiber and drei updates, a proper release could be made. But until that point maybe this will be enough?

2025-01-31 15:56 UTC, FarazzShaikh approved these changes

2025-01-31 15:57 UTC, merged